"""Add receiver_id to Message model

Revision ID: db232bd03527
Revises: 932566e91a7c
Create Date: 2024-02-29 19:21:17.117021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db232bd03527'
down_revision = '932566e91a7c'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # commands auto generated by Alembic - please adjust!
    # with op.batch_alter_table('message', schema=None) as batch_op:
    #    batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
    #   # batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])

    # with op.batch_alter_table('user', schema=None) as batch_op:
    #   batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
    #   batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
    #   batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
    #   batch_op.add_column(sa.Column('receiver_id', sa.Integer(), nullable=False))
    #   batch_op.alter_column('password',
    #                         existing_type=mysql.VARCHAR(length=60),
    #                         nullable=False)
    # batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
    # batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])


#   batch_op.drop_column('profile_picture')

# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', mysql.MEDIUMBLOB(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('password',
                              existing_type=mysql.VARCHAR(length=60),
                              nullable=True)
        batch_op.drop_column('receiver_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###
